// <auto-generated />
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220616162153_mig6")]
    partial class mig6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.About", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsimSoyisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KısaAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutId");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Deneyim", b =>
                {
                    b.Property<int>("DeneyimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalismaSuresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketPozisyon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeneyimId");

                    b.ToTable("Deneyims");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Egitim", b =>
                {
                    b.Property<int>("EgitimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BitirmePuani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BölümAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulCikisTRH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OkulGirisTRH")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EgitimId");

                    b.ToTable("Egitims");
                });

            modelBuilder.Entity("EntityLayer.Concrete.IlgiAlanlari", b =>
                {
                    b.Property<int>("ilgiAlanlarıId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ilgiAlanAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ilgiAlanlarıId");

                    b.ToTable("ılgiAlanlaris");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Yetenekler", b =>
                {
                    b.Property<int>("YetenekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Yetenekisim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YetenekId");

                    b.ToTable("yeteneklers");
                });
#pragma warning restore 612, 618
        }
    }
}
